name: Run CI

on: [push]

jobs:
  start_application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm run dev &

      - name: Wait for application to start
        run: |
          echo "Waiting for the application to start..."
          while ! curl -s http://localhost:5173 > /dev/null
          do
            sleep 5
          done

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run typechecker
        run: npm run tsc

  cypress_run:
    runs-on: ubuntu-latest
    needs: start_application

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test.e2e

      - name: Stop application
        if: always()
        run: pkill -f "npm run dev"
