name: Run Cypress Tests

on:
  push:
    branches:
      - main # Lance les tests lors des push sur la branche main
  pull_request:
    branches:
      - main # Lance les tests lors des pull requests vers la branche main

jobs:
  cypress_run:
    runs-on: ubuntu-latest # Utilise l'image Ubuntu la plus récente

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install # Installe les dépendances du projet

      - name: Build project
        run: npm run build --if-present

      - name: Start application
        run: npm run test.e2e # Démarre l'application en arrière-plan

# Application n'est pas lancé. Et si je la lance, ne passe pas à l'étape suivante
